### ISSUE TITLE
PNG badge creation is broken in non-ASCII characters

### ISSUE THREAD

**Issue by aiotter** [badges/squint#60] opened 2022-02-20 09:03 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

When you use non-ASCII characters as label or message parameter, broken png image is generated.

### 🔗 Link to the badge

https://raster.shields.io/static/v1?label=%E3%83%A9%E3%83%99%E3%83%AB&message=%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8

**Comment by chris48s** [comment] 2022-02-20 12:55
I've transferred this over from https://github.com/badges/shields
It looks like there has been a regression here :(

https://github.com/badges/squint/pull/13 fixed this problem, but now we're back to the same behaviour we were seeing in https://github.com/badges/squint/issues/7 e.g:

- https://raster.shields.io/badge/emoji-%F0%9F%91%8D-blue
- https://raster.shields.io/badge/emoji-%F0%9F%87%B3%F0%9F%87%B4-blue
- https://raster.shields.io/badge/emoji-%F0%9F%90%8F-blue

**Comment by calebcartwright** [comment] 2022-02-20 19:08
> I've transferred this over from https://github.com/badges/shields It looks like there has been a regression here :(
> 
> #13 fixed this problem, but now we're back to the same behaviour we were seeing in #7 e.g:
> 
>     * https://raster.shields.io/badge/emoji-%F0%9F%91%8D-blue
> 
>     * https://raster.shields.io/badge/emoji-%F0%9F%87%B3%F0%9F%87%B4-blue
> 
>     * https://raster.shields.io/badge/emoji-%F0%9F%90%8F-blue

Think these are actually unrelated. I forgot to deploy #13 to prod which is why we're seeing that, e.g. compare to:


- https://squint-staging.herokuapp.com/badge/emoji-%F0%9F%91%8D-blue
![](https://squint-staging.herokuapp.com/badge/emoji-%F0%9F%91%8D-blue)
- https://squint-staging.herokuapp.com/badge/emoji-%F0%9F%87%B3%F0%9F%87%B4-blue
![](https://squint-staging.herokuapp.com/badge/emoji-%F0%9F%87%B3%F0%9F%87%B4-blue)
- https://squint-staging.herokuapp.com/badge/emoji-%F0%9F%90%8F-blue
![](https://squint-staging.herokuapp.com/badge/emoji-%F0%9F%90%8F-blue)

**Comment by chris48s** [comment] 2022-02-20 19:13
I see. Interestingly
https://raster.shields.io/static/v1?label=%E3%83%A9%E3%83%99%E3%83%AB&message=%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8
and
https://squint-staging.herokuapp.com/static/v1?label=%E3%83%A9%E3%83%99%E3%83%AB&message=%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8
are differently broken :upside_down_face:

**Comment by calebcartwright** [comment] 2022-02-20 19:14
I'm sure the differences in font packs between the two are playing at least a partial role, and wouldn't be surprised if a similar type of fix is needed. Just wanted to note the emoji was a pebkac issue on my part and not a regression

**Comment by calebcartwright** [comment] 2022-02-20 19:17
Indeed it works fine on my local machine when running the binary directory, so almost certainly a case of needing to find relevant packages and incorporate them into the docker image that's getting deployed:

![image](https://user-images.githubusercontent.com/13042488/154860181-e72079b0-fc1a-4038-9522-a30cc3cceded.png)


![image](https://user-images.githubusercontent.com/13042488/154860147-74abdf90-3387-4809-adaf-2ab8e7314359.png)

**Closed** 2022-02-21 21:04 UTC
Labels: bug
